### ISSUE TITLE
Feature request: Update date dynamically

### ISSUE THREAD

**Issue by KabbAmine** [iwataka/airnote.vim#1]
I was planning to create a simple note-taking vim plugin until I found yours, and I should say that it suits my usage.

A good feature will be to update the date each time we open an existed note file (Via a configurable option).

**Comment by iwataka** [comment]
Thank you for your request!

It is really a nice feature, but I think it should not be included in Airnote.
I suppose you mean updating date when notes are opened by `:Note` command, but there is at least one problem for this way.

Your notes may be opened by `:grep`, `:Unite` or something other than `:Note` command and then the date remains not updated.

It is a little confusing and useless, so I disagree with implementing this feature in Airnote.

But I have some alternative ways for this problem and my current best answer is like this:

``` vim
let g:airnote_suffix = 'note.md'
fu! s:airnote_bufenter()
  let time = strftime(g:airnote_date_format)
  call setline(1, printf(&commentstring, time))
endfu
augroup vimrc-airnote
  autocmd!
  autocmd BufEnter *.note.md call s:airnote_bufenter()
augroup END
```

Define your own note suffix (maybe you have to rename all your existing notes, sorry) and use auto-commands.
I want to keep Airnote simple and customizable, so this seems to be better way for me.

**Comment by KabbAmine** [comment]
Sure, its up to you :smiley: 

> But I have some alternative ways for this problem and my current best answer is like this:

Thanks for your suggestion, I've currently done something very similar after this issue was created. Update the date only only when the note is saved (It makes more sense)

``` vim
augroup Airnote
    autocmd!
    execute 'autocmd BufWritePost ' . g:vimDir . '/various/*.md :call setline(1, "> " . strftime(g:airnote_date_format))'
augroup END
```

Note that you can use paths in autocommands (`g:vimDir` is the location of my vim config).

Issue closed.

**Comment by iwataka** [comment]
Your way seems to be better than mine:+1:
Maybe I will add this content to Airnote document.

Thank you!

**Comment by KabbAmine** [comment]
Good idea but if you do, use `BufWrite` instead.

**Comment by iwataka** [comment]
Thanks:smile:
